Version 1.0 of web-site
Ev1ch/web-lab-1 pull request #1
Opened 2021-09-08 12:59 UTC by Ev1ch

2021-09-14 16:15 UTC, nosovk commented on about.html
> +        <link rel="stylesheet" href="css/styles.css">
css/syles =>/css/styles
тут нужен скорее всего absolute path, т.к. может сломаться если больше таких html попадут еще в подпапки

2021-09-14 16:15 UTC, nosovk commented on about.html
> +        <div class="container">
прекрасный класс, наполненный смыслом. А нужен ли тебе этот див если body есть?

2021-09-14 16:16 UTC, nosovk commented on about.html
> +                <div class="header__description">
это прямо BEM :)
возможно модификатор header__ не нужен?

2021-09-14 16:17 UTC, nosovk commented on contacts.html
> +                <a class="navigation__link" href="index.html">Home</a>
избыточные классы
.navigation и .navigation__link
лучше использовать абсолютные ссылки от корня сайта для href

2021-09-14 16:19 UTC, nosovk commented on css/normalize.css
> +html {
его кстати можно из npm брать

2021-09-14 16:20 UTC, nosovk commented on css/components/navigation.css
> +.navigation__link::before {
посмотри на штуки типа scss, там прямо есть хорошие подходы чтобы так не делать

2021-09-14 16:21 UTC, nosovk requested changes
рекомендую подключить scss
остались все работы по линтерам и хаски и т.п.

2021-09-14 16:38 UTC, Ev1ch commented on about.html
> +                <div class="header__description">
А як тоді цей опис відрізнити від інших? Просто вкладеністю?

2021-09-14 16:38 UTC, Ev1ch commented on contacts.html
> +                <a class="navigation__link" href="index.html">Home</a>
Пропонуєте просто .navigation .link?

2021-09-14 16:40 UTC, Ev1ch commented on about.html
> +        <div class="container">
Можна і без нього, але і в ньому не бачу нічого поганого

2021-09-14 18:02 UTC, nosovk commented on .stylelintrc
> +    "extends": "stylelint-config-standard",
https://github.com/kristerkari/stylelint-high-performance-animation

2021-09-14 18:38 UTC, nosovk commented on about.html
> +        <div class="container">
если будут елементы за сеткой, то можно будет и враппер добавить… premature optimization is a sin...

2021-09-14 18:39 UTC, nosovk commented on contacts.html
> +                <a class="navigation__link" href="index.html">Home</a>
хуже
```
nav a {}
```
если это семантичный блок

2021-09-15 22:02 UTC, nosovk commented on package.json
> +        "jslint": "npx eslint \"js/**/*.js\"",
npx не нужен, скрипты сразу выплоняются с path установленным в bin пакетов

2021-09-15 22:36 UTC, Ev1ch commented on package.json
> +        "jslint": "npx eslint \"js/**/*.js\"",
На Windows просто `eslint ...` не працює, прописати шлях в .bin краще?

2021-10-09 16:19 UTC, nosovk commented on .github/workflows/main.yml
> +        uses: actions/setup-node@v2
use cache for node modules

2021-10-31 16:45 UTC, nosovk commented on about.html
> +        <base href="./" />
это как раз скорее всего не верная конструкция, поставь / или если в этой репе одна лаба - удали вообще.

2021-10-31 16:46 UTC, nosovk commented on package.json
> +        "format": "prettier --check .",
он тоже умеет в --ignore-path

2021-10-31 16:46 UTC, nosovk commented
поправить коммент и сливать

2022-01-15 11:29 UTC, merged